<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE bookstore [

<!ELEMENT bookstore (genre+)>
<!ATTLIST genre name CDATA #IMPLIED>
<!ELEMENT genre (book+)>
<!ELEMENT book (chapter+)>
<!ATTLIST book ISBN CDATA #IMPLIED>
<!ATTLIST book Title CDATA #IMPLIED>
<!ATTLIST book Price CDATA #IMPLIED>
<!ELEMENT chapter (#PCDATA)>
<!ATTLIST chapter num CDATA #IMPLIED>
<!ATTLIST chapter name CDATA #IMPLIED>
]>

<bookstore>

    <genre name="Fiction">
  
      <book ISBN="10-861003-324" Title="A Tale of Two Cities" Price="19.99">
  
        <chapter num="1" name="Introduction">
  
          Abstract...
  
        </chapter>
  
        <chapter num="2" name="Body">
  
          Abstract...
  
        </chapter>
  
        <chapter num="3" name="Conclusion">
  
          Abstract...
  
        </chapter>
  
      </book>
  
      <book ISBN="1-861001-57-5" Title="Pride And Prejudice" Price="24.95">
  
        <chapter num="1" name="Introduction">
  
           Abstract...
  
        </chapter>
  
        <chapter num="2" name="Body">
  
          Abstract...
  
        </chapter>
  
        <chapter num="3" name="Conclusion">
  
          Abstract...
  
        </chapter>
  
      </book>
  
    </genre>
  
    <genre name="NonFiction">
  
      <book ISBN="10-861003-324" Title="Statistics of Two Cities" Price="19.99">
  
        <chapter num="1" name="Introduction">
  
          Abstract...
  
        </chapter>
  
        <chapter num="2" name="Body">
  
          Abstract...
  
        </chapter>
  
        <chapter num="3" name="Conclusion">
  
           Abstract...
  
        </chapter>
  
      </book>
  
      <book ISBN="1-861001-57-6" Title="The Sea: becoming an Old Man and the Sea" Price="27.95">
  
        <chapter num="1" name="Introduction">
  
          Abstract...
  
        </chapter>
  
        <chapter num="2" name="Body">
  
          Abstract...
  
        </chapter>
  
        <chapter num="3" name="Conclusion">
  
          Abstract...
  
        </chapter>
  
      </book>
  
    </genre>
  
  </bookstore>